### ISSUE TITLE
When using DataBus there is an exception on Blob with status code 412

### ISSUE THREAD

**Issue by BadiSatwa** [rebus-org/Rebus.AzureStorage#10]
Hi,

Our situation is like this:

- We are using Azure Service Bus
- Sending file by DataBus using Azure Storeage Blob
- There are multiple subscribers that read data attachment at the same time (or very close times)

From time to time we have an exception:
Microsoft.Azure.Storage.StorageException: The condition specified using HTTP conditional header(s) is not met.
   at Microsoft.Azure.Storage.Core.Executor.Executor.ExecuteAsync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext, CancellationToken token)
   at Microsoft.Azure.Storage.Blob.BlobReadStream.DispatchReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at Microsoft.Azure.Storage.Blob.BlobReadStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.CopyTo(Stream destination, Int32 bufferSize)

Return status is 412 and message is landing in error queue.

What do you think about that?

Kind Regards,
Piotr Balas

**Comment by Efp95** [comment]
I'm having the same issue. Is it any update regarding this?

**Comment by mookid8000** [comment]
Ah damn, this must be because each reader tries to update the last-read-time property of the blob, and then they run into a race condition.

The correct action in this case would be to simply ignore the etag of the blob when updating the last-read-time, because in this case, the last one to write is always right. 🙂

I can probably fix this within a couple of days, but a PR is also most welcome.

**Comment by mookid8000** [comment]
Could you try Rebus.AzureStorage 4.3.1 and see if it's fixed? (I think it is 🙂 )
