### ISSUE TITLE
Unhandled exception. System.TypeLoadException: Method 'get_NetworkTimeout' 

### ISSUE THREAD

**Issue by jfalameda** [rebus-org/Rebus.AzureStorage#11]
Hi, I get the following error when running on .NET core 3.1

OS: Mac OSX Catalina

As for the initialization I am doing a simple one:

```
var activator = new BuiltinHandlerActivator();
            Configure.With(activator)
                .Logging(l => l.Serilog())
                .Transport(t => t.UseAzureStorageQueues(connectionString, "request-appointment-saga"))
                .Start();
```

Below, the exception I got:

```
Unhandled exception. System.TypeLoadException: Method 'get_NetworkTimeout' in type 'Microsoft.Azure.Storage.Queue.QueueRequestOptions' from assembly 'Microsoft.Azure.Storage.Queue, Version=11.1.1.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
   at Microsoft.Azure.Storage.Queue.CloudQueueClient..ctor(StorageUri storageUri, StorageCredentials credentials, DelegatingHandler delegatingHandler)
   at Microsoft.Azure.Storage.Queue.QueueAccountExtensions.CreateCloudQueueClient(CloudStorageAccount account)
   at Rebus.Config.AzureStorageQueuesConfigurationExtensions.Register(StandardConfigurer`1 configurer, String inputQueueAddress, CloudStorageAccount cloudStorageAccount, AzureStorageQueuesTransportOptions optionsOrNull)
   at Rebus.Config.AzureStorageQueuesConfigurationExtensions.UseAzureStorageQueues(StandardConfigurer`1 configurer, String storageAccountConnectionString, String inputQueueAddress, AzureStorageQueuesTransportOptions options)
   at Appointment.Program.<>c__DisplayClass2_0.<ConfigureQueueListeners>b__1(StandardConfigurer`1 t) in /Users/josefa/projects/Ally/DHCloud/Appointment/Program.cs:line 74
   at Rebus.Config.RebusConfigurer.Transport(Action`1 configurer)
```

**Comment by mookid8000** [comment]
I don't understand precisely how you can get the exception you've posted here, but it looks like your program is running with a version of Microsoft.Azure.Storage.Queue whose `QueueRequestOptions` class does not have the  `NetworkTimeout` property.

Rebus only uses this property indirectly, as it's invoked by `QueueRequestOptions` in its own constructor. I really don't get it.

I've released Rebus.AzureQueues 1.1.0 though, where I've updated the Microsoft.Azure.Storage.Queues dependency to 11.2.2 – could you try and see if it changes anything?

**Comment by mookid8000** [comment]
Hi @jfalameda , I assume your problem went away 🙂  if not, please don't hesitate to bring it up again
